### ISSUE TITLE
Update app_updates for MySIMBL 0.5.3

### ISSUE THREAD

**Issue by duggum** [w0lfschild/app_updates#2]
Just an FYI...

The Homebrew Cask file for MySIMBL relies on your app-updates repo to keep itself updated. I submitted a pull request to Hombrew Cask to update MySIMBL using the direct release download link from the MySIMBL repo, but their cask file still uses your appcast.xml file for updates.

Cheers!

**Comment by w0lfschild** [comment]
Noted, thanks for the heads up.

**Comment by software-network** [comment]
@w0lfschild  Will this break my Mac is I do this?

**Comment by w0lfschild** [comment]
@ghost no
