### ISSUE TITLE
Typo in latest Flashlight filename

### ISSUE THREAD

**Issue by j6k4m8** [w0lfschild/app_updates#6]
This release is named [Flashlight_maste.zip](https://github.com/w0lfschild/app_updates/blob/master/Flashlight/Flashlight_maste.zip) (missing the last `r` in `master`) so the links from https://www.macenhance.com/flashlight fail. I'd take out a PR but seems like a lot of unnecessary fork/process just to add a letter to a filename :)

**Comment by w0lfschild** [comment]
Thanks! Fixed.
