### ISSUE TITLE
macForge com.apple.security.libraryvalidation.plist does not exist

### ISSUE THREAD

**Issue by clankill3r** [w0lfschild/app_updates#8]
When laucnhing macForge I get the following:

![Screenshot 2020-12-04 at 12 05 18](https://user-images.githubusercontent.com/738650/101156577-1b07ff00-3629-11eb-8ea1-628ac79c1fd9.png)

But:

![Screenshot 2020-12-04 at 12 05 12](https://user-images.githubusercontent.com/738650/101156644-2eb36580-3629-11eb-8b84-a98e4bdf1343.png)

Does not exist.

OSX 10.14.6

**Comment by w0lfschild** [comment]
Yes the file does not exist by default. Run the command in terminal.
